config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  authenticated :admin do
    root 'backoffice#index', as: :authenticated_root
  end

  unauthenticated :admin do
     root 'humans#new', as: :unauthenticated_root
  end

  
  resources :humans, only: [:create]

  get 'backoffice' => 'backoffice#index'

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/human.rb
class Human < ApplicationRecord
    #validates :name, uniqueness: true
    validates :name, :country, presence: true
    validates :skill, :knowledge, inclusion: { in: [ true, false ] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	
	add_flash_types :danger, :success

  	protected
  	def after_sign_in_path(resource)
  		backoffice_path
  	end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	
	before_action :authenticate_admin!

	def index
		if (params[:search] && params[:search] != "")
			@humans = Human.where(country: params[:search]).page(params[:page]).per(60)
		else
			@humans = Human.page(params[:page]).per(60)
		end
	end	
end

app/controllers/humans_controller.rb
class HumansController < ApplicationController

  def new  
    @human = Human.new
  end

  def create
    @human = Human.new(human_parms)

    if @human.save
      redirect_to unauthenticated_root_path, notice: "Formulario respondido com sucesso!"
    else
      redirect_to unauthenticated_root_path, danger: "Por favor, preencha todos os campos"
    end
  end

  private

  def human_parms
    params.require(:human).permit(:name, :country, :knowledge, :skill, :q1, :q2, :q3, :q4, :q5, :q6)
  end
end

app/helpers/backoffice_helper.rb
module BackofficeHelper
end

app/helpers/humans_helper.rb
module HumansHelper
end

app/views/backoffice/index.html.erb
<div class="backoffice-container">
	<h1>Bem vindo Administrador!</h1>
	<br>
	<%=	form_tag(backoffice_path, :method => :get) do %>
		<%= country_select nil, :search, include_blank: true %>
		<%= submit_tag "Filtrar" , class:"btn btn-success btn-sm"%>
	<% end %>
	<br>

	<table class="table table-responsive">
	  	<thead>
		    <tr>
		      <th colspan="4">Aluno:</th>
		      <th colspan="4">País</th>
		      <th colspan="4">Conhecimento:</th>
		      <th colspan="4">Instrumento:</th>
		      <th colspan="4">Questão 1</th>
		      <th colspan="4">Questão 2</th>
		      <th colspan="4">Questão 3</th>
		      <th colspan="4">Questão 4</th>
		      <th colspan="4">Questão 5</th>
		      <th colspan="4">Questão 6</th>

		    </tr>
	  	</thead> 	
      	<tbody>
	      <% @humans.each do |human| %>
	        <tr>
		        <td colspan="4"><%= human.name %></td>
		        <td colspan="4"><%= human.country %></td>
		        <td colspan="4">
		        	<% if human.knowledge? %>
		        		<div>SIM</div>
		        	<% else %>
		        		<div>NÃO</div>
		        	<% end %>
		        </td>
		        <td colspan="4">
		        	<% if human.skill? %>
		        		<div>SIM</div>
		        	<% else %>
		        		<div>NÃO</div>
		        	<% end %>
		        </td>
		        <td colspan="4"><%= human.q1 %></td>
		        <td colspan="4"><%= human.q2 %></td>
		        <td colspan="4"><%= human.q3 %></td>
		        <td colspan="4"><%= human.q4 %></td>
		        <td colspan="4"><%= human.q5 %></td>
		        <td colspan="4"><%= human.q6 %></td>
		    </tr>
	      <% end %>
      </tbody>
   </table>
	<%= paginate (@humans), theme: 'twitter-bootstrap-4' %>
	<%= link_to "Sair", destroy_admin_session_path, method: 'delete', class:"btn btn-success btn-sm"%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Form</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">

      <!--
      <% if notice %>
        <p class="notice"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert"><%= alert %></p>
      <% end %>-->
      
      <%= yield %>
    </div>
  </body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script type="text/javascript" src="path/to/jquery.mobile-events.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-touch-events/1.0.5/jquery.mobile-events.js"></script>
  
</html>